import { 
  Gamepad2, 
  Users, 
  Trophy, 
  UserCircle, 
  LogOut, 
  Menu, 
  X, 
  Play, 
  Star, 
  TrendingUp, 
  History, 
  Shield, 
  Search, 
  Filter, 
  ChevronRight, 
  ChevronLeft, 
  MessageSquare, 
  UserPlus, 
  Check, 
  Clock, 
  RefreshCcw, 
  Cpu, 
  Circle,
  HandMetal,
  Hand,
  Scissors,
  RotateCcw,
  Settings,
  Share2,
  Info
} from 'lucide-react';

const ICON_MAP = {
  games: Gamepad2,
  friends: Users,
  leaderboard: Trophy,
  profile: UserCircle,
  logout: LogOut,
  menu: Menu,
  close: X,
  play: Play,
  star: Star,
  trending: TrendingUp,
  history: History,
  shield: Shield,
  search: Search,
  filter: Filter,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  message: MessageSquare,
  addFriend: UserPlus,
  check: Check,
  clock: Clock,
  refresh: RefreshCcw,
  bot: Cpu,
  circle: Circle,
  rock: HandMetal,
  paper: Hand,
  scissors: Scissors,
  reset: RotateCcw,
  settings: Settings,
  share: Share2,
  info: Info,
  chess: Trophy,
  poker: HandMetal
};

export default ICON_MAP;
